### ISSUE TITLE
Python Error 'KeyError: entry-name" in Brocade_zoning.py

### ISSUE THREAD

**Issue by nmandy-git** [brocade/ansible#34]
Hi,

Im trying to add members into an existing peerzone using :
```
- name: Add members to zone
    brocade_zoning_zone:
        credential: "{{credential}}"
        vfid: -1
        zones: "{{zones}}"
        members_add_only: True
```

Where `{{zones}}` is : 

```
 zones": [`
        {
            "members": [
                "alias2"
            ], 
            "name": "peerzone_2"
        }, 
        {
            "members": [
                "alias2"
            ], 
            "name": "peerzone_1"
        }
    ]
}
```

This is the error output:

`in zone_process_diff
KeyError: 'entry-name'`

This is the code involved IMHO, from brocade_zone.py:

```
            if zone["name"] == c_zone["zone-name"]:
                found_in_c = True
                added_members, removed_members = process_member_diff(
                    result, zone["members"],
                    c_zone["member-entry"]["entry-name"])
```

Finally, this is my peerzone, created manually (gathered from API) : 

```
        <zone>
            <zone-name>peerzone_1</zone-name>
            <zone-type>1</zone-type>
            <member-entry>
                <principal-entry-name>principal-alias</principal-entry-name>
            </member-entry>
        </zone>
```

Thanks in advance,
Regards,
Nico

**Comment by nmandy-git** [comment]
Ok, found out what the problem is.

Peerzone must have at least one principal-member (that is normal) AND one member.

I don't know if this is planned or not.

**Comment by daniel-chung-broadcom** [comment]
Let me find out and get back to you.

**Comment by daniel-chung-broadcom** [comment]
to clarify

1) you started with a peer zone that contains more than one member & one principal member
2) you tried to add just one more member and this failed
3) when you tried to add one more member and one more principal member, that worked ok.

??

**Comment by nmandy-git** [comment]
> 
> 
> to clarify
> 
>     1. you started with a peer zone that contains more than one member & one principal member
> 
>     2. you tried to add just one more member and this failed
> 
>     3. when you tried to add one more member and one more principal member, that worked ok.
> 
> 
> ??

Nope:
1. I created a peerzone with a principal member
2. Tried to add a members > Failed
3. Added manually a member in that peerzone, now addition of new member works through Ansible

I think I'll redo that, in a well and proper manner to be sure.

**Comment by daniel-chung-broadcom** [comment]
Thanks for the info.

I think I may have also recreated the issue. I see the following error.

  File "/tmp/ansible_brocade_zoning_zone_payload_p4ixx16r/ansible_brocade_zoning_zone_payload.zip/ansible/modules/brocade_zoning_zone.py", line 168, in zone_process_diff
KeyError: 'entry-name'

basically, I started with playbook with one principal member only with members_add_only option. Then I updated the playbook with one member only with members_add_only option. The second playfailed. 

I believe this is along the line of what you are seeing as well.

**Comment by daniel-chung-broadcom** [comment]
I have some changes that should address your issues. I pushed the changes to

snmp_config_new_throttle

branch. Can you try out the branch and see if this address this issue? I verified

1) created peer zone with one pmember
2) add one member only
3) add one pmember only
4) add one member only
5) add one member & one pmember

Thanks.

**Comment by nmandy-git** [comment]
Ok, I reproduced the problem. So I can confirm, that a peerzone w/o any members isn't working properly (tested in in defined configuration).
I add a single random member and thats working.
Im gonna give a look to your branch. 
As I'm working in a custom env., can't pull easily. 

I'll try to keep you updated

**Comment by nmandy-git** [comment]
Still the same error :/
It seems even worse, not working at all.
Did you try with an existing peerzone? Or maybe I need to set something else?
Now, even with an existing peerzone and a pmember + a member, it does not work.

**Comment by daniel-chung-broadcom** [comment]
I must have misunderstood the scenario then. What I tested as

1) start with empty zone database
2) using ansible, create one peerzone with one principal member
3) using ansible, add to the existing peerzone from #2 one member.

Do you mind sharing the playbook? Also, would it be possible for you to run the play using -vvvv option and send me the output? I'll retry to see if I could repro the scenario using your configuration.

**Comment by nmandy-git** [comment]
> 
> 
> Still the same error :/
> It seems even worse, not working at all.
> Did you try with an existing peerzone? Or maybe I need to set something else?
> Now, even with an existing peerzone and a pmember + a member, it does not work.

Ok, I failed a little bit here. So, when both of my 2 zones are filled with a pmember and a member it does work. If one zone is not configured as mentionned, no zone is modified. I tried with a good and a bad zone (one with member the other without).

So still the same behaviour.

I can provide you the following as it's really simple:
What I have:
- cfg: cfg1 (enabled)
- zone: peerzone1 -  pmember1 & member1 > In active cfgzone member
- zone: peerzone2 - pmember2
- zone: peerzone3 - pmember3
- aliases: 
----those of peerzone1 are OK
---- pmember2
---- pmember3

What I do:
1. Create alias of member2 > Thats OK
2. Add alias in each peerzones with following code:

```
- name: Create aliases
  brocade_zoning_alias:
    credential: "{{credential}}"
    vfid: -1
    aliases: "{{aliases}}"
    members_add_only: True

- name: Create zones
  brocade_zoning_zone:
    credential: "{{credential}}"
    vfid: -1
    zones: "{{zones}}"
    members_add_only: True

- name: Create cfgs
  brocade_zoning_cfg:
    credential: "{{credential}}"
    vfid: -1
    cfgs: "{{newcfg}}"
    members_add_only: True
```

With `"{{zones}}"` :
```
zones": [
        {
            "members": [
                "member2"
            ], 
            "name": "peerzone2"
        }, 
        {
            "members": [
                "member2"
            ], 
            "name": "peerzone3"
        }
    ]
}
```

3. Add peerzones 2 & 3 into a new cfg: newcfg
4. Not enabling newcfg atm.

Goal:
- cfg: cfg1 (enabled) + newcfg 
- zone: peerzone1 -  pmember1 & member1 > In active cfgzone member
- zone: peerzone2 - pmember2 & member2 > In newcfg cfgzone member
- zone: peerzone3 - pmember3 & member2 > In newcfg cfgzone member

As I stated above, aliases and cfgs creation are OK. Only problem is if my peerzones (peerzones2 and peerzones3 in example) got a pmember (which is required) but no members.

The output is really small (greping out the Ansiballz things) :
`in zone_process_diff
KeyError: 'entry-name'`

**Comment by daniel-chung-broadcom** [comment]
I tried to repre the steps as described and I am still not able to for some reason. 

I started with empty zoning db. Then I executed the following playbook.

dc400196@iaas-l-2206-611:~/ansible/tasks$ cat test.yml
---

# Copyright 2019 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: san_eng_zone_seed_san_a
  gather_facts: False

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: admin
      fos_password: fibranne
      https: False
    aliases:
      - name: pmember1
        members:
          - aa:11:11:11:11:11:11:11
      - name: member1
        members:
          - aa:44:44:44:44:44:44:44      
    zones:
      - name: peerzone1
        members:
          - member1
        principal_members:
          - pmember1
      - name: peerzone2
        principal_members:
          - pmember1
      - name: peerzone3
        principal_members:
          - pmember1

  tasks:

  - name: Create aliases
    brocade_zoning_alias:
      credential: "{{credential}}"
      vfid: -1
      aliases: "{{aliases}}"

  - name: Create zones
    brocade_zoning_zone:
      credential: "{{credential}}"
      vfid: -1
      zones: "{{zones}}"

and my zone db looks correct after the play.

switch_name:FID128:admin> cfgshow
Defined configuration:
 zone:  peerzone1
                pmember1; member1
 zone:  peerzone2
                pmember1
 zone:  peerzone3
                pmember1
 alias: member1 aa:44:44:44:44:44:44:44
 alias: pmember1
                aa:11:11:11:11:11:11:11

Effective configuration:
 no configuration in effect

Then I executed any playbook that is supposed to add the member to peerzone2 & peerzone3.

dc400196@iaas-l-2206-611:~/ansible/tasks$ cat test1.yml
---

# Copyright 2019 Broadcom. All rights reserved.
# The term 'Broadcom' refers to Broadcom Inc. and/or its subsidiaries.
# GNU General Public License v3.0+
# (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)


- hosts: san_eng_zone_seed_san_a
  gather_facts: False

  vars:
    credential:
      fos_ip_addr: "{{fos_ip_addr}}"
      fos_user_name: admin
      fos_password: fibranne
      https: False
    aliases:
      - name: pmember1
        members:
          - aa:11:11:11:11:11:11:11
      - name: member1
        members:
          - aa:44:44:44:44:44:44:44      
    zones:
      - name: peerzone1
        members:
          - member1
        principal_members:
          - pmember1
      - name: peerzone2
        members:
          - member1
        principal_members:
          - pmember1
      - name: peerzone3
        members:
          - member1
        principal_members:
          - pmember1

  tasks:

  - name: Create aliases
    brocade_zoning_alias:
      credential: "{{credential}}"
      vfid: -1
      aliases: "{{aliases}}"

  - name: Create zones
    brocade_zoning_zone:
      credential: "{{credential}}"
      vfid: -1
      zones: "{{zones}}"
      members_add_only: True

and I see the following zone db output afterward.

switch_name:FID128:admin> cfgshow
Defined configuration:
 zone:  peerzone1
                pmember1; member1
 zone:  peerzone2
                pmember1
 zone:  peerzone3
                pmember1
 alias: member1 aa:44:44:44:44:44:44:44
 alias: pmember1
                aa:11:11:11:11:11:11:11

Effective configuration:
 no configuration in effect

Do you see anything specific that I am doing differently here to repro the problem?

Thanks.

**Comment by daniel-chung-broadcom** [comment]
sorry. copied the wrong cfgshow output. Here is the show output after doing the second playbook.

switch_name:FID128:admin> cfgshow
Defined configuration:
 zone:  peerzone1
                pmember1; member1
 zone:  peerzone2
                pmember1; member1
 zone:  peerzone3
                pmember1; member1
 alias: member1 aa:44:44:44:44:44:44:44
 alias: pmember1
                aa:11:11:11:11:11:11:11

Effective configuration:
 no configuration in effect

**Comment by daniel-chung-broadcom** [comment]
Can you please confirm the line #302 in library/brocade_zoning_zone.py? It looks like this, right?

                if ("members" in zone and "entry-name" in c_zone["member-entry"]):

**Comment by nmandy-git** [comment]
Wow, I'm an ape... I pulled the master branch...
I've just copy/paste the zoning_zone.py in my env, and thats working :)
I apologize for your time.

Thanks for the debug, i'm waiting for the merge with master branch or the update.

Regards,
Nico

**Comment by daniel-chung-broadcom** [comment]
no problem. glade to see that the original issue was addressed with the changes. 

I plan to do another merge to master toward the end of the week, along with other accumulative changes. So, these specific changes should be in the master by next week. 

Thanks for reporting the issue and helping with the debug.
